wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
dependencies:
- smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
networks:
  goerli:
    priceFeedAddress: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: True
  mainnet-fork:
    priceFeedAddress: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False